### ISSUE TITLE
Guava version is out of date for robolectric

### ISSUE THREAD

**Issue by mmw125** [sky-map-team/stardroid#377]
I get this error on `LatLongRoboTest`, `ZoomControllerTest`, `TransitioningCompositeClockTest`, and `PlanetTest` when running the tests at head.

```
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.sortedCopyOf(Ljava/util/Comparator;Ljava/lang/Iterable;)Lcom/google/common/collect/ImmutableList;

	at org.robolectric.internal.bytecode.ShadowProviders.<init>(ShadowProviders.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.util.inject.Injector.inject(Injector.java:239)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:221)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:485)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:213)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:197)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:191)
	at org.robolectric.internal.SandboxTestRunner.<init>(SandboxTestRunner.java:75)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:101)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:96)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:125)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:111)
	at com.intellij.junit4.JUnit46ClassesRequestBuilder.collectWrappedRunners(JUnit46ClassesRequestBuilder.java:86)
	at com.intellij.junit4.JUnit46ClassesRequestBuilder.getClassesRequest(JUnit46ClassesRequestBuilder.java:47)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:86)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:46)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

Looks like robolectrric is trying to use SortedCopyOf, [which was only added in version 21 of guava], (https://guava.dev/releases/23.0/api/docs/com/google/common/collect/ImmutableList.html#sortedCopyOf-java.lang.Iterable-), but the Guava version being used in the project is 19.

Updating the guava version past 21 fixes the issue.

**Comment by jaydeetay** [comment]
What's the exact command you're running Mark? I can't repro this with a fresh pull...nor can I see it occuring on Cirrus or Travis (though nothing I do seems to break the latter so I don't trust it).

**Comment by mmw125** [comment]
I am just running the tests as a Android JUnit test in Android Studio. Here's the configuration that I have.

![image](https://user-images.githubusercontent.com/1638216/97120538-1bd67880-16ee-11eb-8cf2-89cd7a81cf10.png)

**Comment by jaydeetay** [comment]
Thanks. Bringing this up to date is likely the right thing to do... I'm
just trying to improve the testing picture before doing a big big
refactoring and it bothers me when things fail but aren't detected.  I'll
try it from the IDE and see what happens.

**Comment by jaydeetay** [comment]
Seems to only happen when running from Android Studio. Curious.
Other puzzled people: https://github.com/robolectric/robolectric/issues/5147

**Comment by jaydeetay** [comment]
Fixed.

**Comment by UmeshChakre** [comment]
i have guava version 28.
i used these 2 dependencies

    implementation("com.google.guava:guava:28.0-android")

    api 'com.google.guava:guava:28.0-android'

I still get same error while running any tests containing robolectric



`java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.sortedCopyOf(Ljava/util/Comparator;Ljava/lang/Iterable;)Lcom/google/common/collect/ImmutableList;

	at org.robolectric.internal.bytecode.ShadowProviders.<init>(ShadowProviders.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.util.inject.Injector.inject(Injector.java:239)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:221)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:485)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:213)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:197)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:191)
	at org.robolectric.internal.SandboxTestRunner.<init>(SandboxTestRunner.java:75)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:101)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:96)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
`


help me, im stuck for days in this.
